<?php
namespace Codwelt\SIMI\SDK\Tests;
use PHPUnit\Framework\TestCase as Father;
/**
 * Class TestCase
 * @package Codwelt\SIMI\SDK\Tests
 * @author Juan Diaz <iam@furiosojack.com>
 */
class TestCase extends Father
{


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->loadEnvs();
    }

    private function loadEnvs()
    {
        $filename = __DIR__."/testing.env.php";
        $vars = array();
        if (file_exists($filename)) {
            $vars = require($filename);

            foreach ($vars as $varKey => $varValue){
                putenv($varKey."=".$varValue."");
            }

        }
    }

}