<?php
namespace Codwelt\SIMI\SDK\InfraStructure\Requests;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseDetalleInmueble;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseFiltroInmueble;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseRepository;

/**
 * Es la peticion que se engenera para solicitar los inmuebles
 * Class RequestFiltroInmuebles
 * @package Codwelt\SIMI\SDK\InfraStructure\Requests
 * @author Juan Diaz <iam@furiosojack.com>
 */
class RequestFiltroInmuebles extends HttpClient
{


    public function ejecutar(array $parameters): ResponseRepository
    {
        $permitidos = array(
            "departamento",
            "ciudad",
            "zona",
            "barrio",
            "tipoInm",
            "tipOper",
            "areamin",
            "areamax",
            "valmin",
            "valmax",
            "banios",
            "garajes",
            "alcobas",
            //ordenar
            "order",
            "campo",
            //limites
            "limite",
            "cantidad"
        );

        foreach ($parameters as $filter => $value){

            if(!in_array($filter,$permitidos)){
                throw new \Exception("Filtro ($filter) no esta permitido en APISIMI");
            }
        }

        $default = [
            "cantidad" => 30,
            "limite" => 1
        ];

        $filtros = array_merge($default,$parameters);
        $valores = "";

        foreach ($filtros as $filtroK => $value){
            $valores =  $valores. "/".$filtroK . "/" .$value;
        }

        $this->endPoint = "v2.1.1/filtroInmueble".$valores;
        return new ResponseFiltroInmueble($this->send()); // TODO: Change the autogenerated stub
    }
}