<?php
namespace Codwelt\SIMI\SDK\InfraStructure\Requests;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseDetalleInmueble;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseFiltroInmueble;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseRepository;

/**
 * Es la peticion que se engenera para solicitar los inmuebles
 * Class RequestFiltroInmuebles
 * @package Codwelt\SIMI\SDK\InfraStructure\Requests
 * @author Juan Diaz <iam@furiosojack.com>
 */
class RequestFiltroInmuebles extends HttpClient
{

    /**
     * @param string $url
     * @return ResponseFiltroInmueble
     * @throws \Exception
     */
    public function ejecutar(string $url): ResponseRepository
    {
        return new ResponseFiltroInmueble(parent::sendGet($url)); // TODO: Change the autogenerated stub
    }
}