<?php


namespace Codwelt\SIMI\SDK\InfraStructure\Requests;

use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseFiltroInmueble;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseGetBarrios;
use Codwelt\SIMI\SDK\InfraStructure\Responses\ResponseRepository;

/**
 * Class RequestGetBarrios
 * @package Codwelt\SIMI\SDK\InfraStructure\Requests
 * @author Juan Diaz <iam@furiosojack.com>
 */
class RequestGetBarrios extends HttpClient
{

    /**
     * Devuelve el listado de barrios
     * @param string $url
     * @return ResponseGetBarrios
     * @throws \Exception
     */
    public function ejecutar(string $url): ResponseRepository
    {
        return new ResponseGetBarrios(parent::sendGet($url)); // TODO: Change the autogenerated stub
    }
}