<?php


namespace Homlity\SIMI\SDK\InfraStructure\Requests;

use Homlity\SIMI\SDK\InfraStructure\Responses\ResponseFiltroInmueble;
use Homlity\SIMI\SDK\InfraStructure\Responses\ResponseGetBarrios;
use Homlity\SIMI\SDK\InfraStructure\Responses\ResponseRepository;

/**
 * Class RequestGetBarrios
 * @package Homlity\SIMI\SDK\InfraStructure\Requests
 * @author Juan Diaz <iam@furiosojack.com>
 */
class RequestGetBarrios extends HttpClient
{

    /**
     * Devuelve el listado de barrios
     * @param string $url
     * @return ResponseGetBarrios
     * @throws \Exception
     */
    public function ejecutar(array $parameters = []): ResponseRepository
    {
        if(empty($parameters["idCiudad"])){
            throw new \Exception("El id de la ciudad es necesaria para obtener los barrios");
        }
        $this->endPoint =  "v2/barrios/idCiudad/".$parameters["idCiudad"];
        return new ResponseGetBarrios($this->send()); // TODO: Change the autogenerated stub
    }
}