<?php


namespace Codwelt\SIMI\SDK\Domain\API;

use Codwelt\SIMI\SDK\Domain\ModelRepository\Inmueble;
use Codwelt\SIMI\SDK\InfraStructure\API\ApiFachada;

/**
 * Class ApiModelRepositoryFachada
 * @package Codwelt\SIMI\SDK\Domain\API
 * @author Juan Diaz <iam@furiosojack.com>
 */
class ApiModelRepositoryFachada extends ApiFachada
{

    /**
     * @param array $filters
     * @return array
     * @throws \Exception
     */
    public function getInmuebles(array $filters = array())
    {
        $return = parent::getInmuebles($filters); // TODO: Change the autogenerated stub

        $inmuebles = array_map(function($inmueble){
            return new Inmueble($inmueble);
        },$return["inmuebles"]);

        $return["inmuebles"] = $inmuebles;
        return $return;
    }
}